name: build

permissions:
  contents: write

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-14
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        if: matrix.os == 'windows-latest'
        with:
          msystem: MINGW64
          update: true
          path-type: inherit
          install: >-
            mingw-w64-x86_64-gn
      - name: ubuntu install
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install ninja-build git clang python3 -y
      - name: macos install
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install ninja

      - name: build-${{ matrix.target }}
        if: matrix.os != 'windows-latest'
        shell: "bash"
        run: |
          bash build.sh ${{ matrix.target }}

      - name: build-windows
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          mkdir dist
          cp $(which gn) dist/gn
          ls -lh dist
          tar -czf ./gn-${{ matrix.target }}.tar.gz -C dist .
          ls -l ./gn-${{ matrix.target }}.tar.gz
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: gn-${{ matrix.target }}
          path: ./gn-${{ matrix.target }}.tar.gz
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: gn
          pattern: gn*
          merge-multiple: true

      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "gn/*.tar.gz"
